### ISSUE TITLE
Toppings Filter - Mushrooms appears multiple times

### ISSUE THREAD

**Issue by gregdeane** [wesbos/master-gatsby#42]
There's a strange issue with the Toppings Filter whereby "Mushrooms" appears multiple times. I've traced it to the fact that "Mushrooms" has two different IDs.

I would submit a PR but I'm not entirely clear on how the topping IDs are generated since they don't match what is contained in `all-sample-data.gz`. I assume it's Sanity that adds the ID but I might be wrong.

## Toppings Filter with two "Mushrooms"
This screenshot is taken from the video itself.
<img width="668" alt="Screen Shot 2020-09-30 at 10 56 08" src="https://user-images.githubusercontent.com/4949000/94665349-4fe79500-030c-11eb-8107-aacf8ed5fae6.png">

## When clicking either "Mushrooms" filter, the total number (5 count) items appear
![Screen Shot 2020-09-30 at 10 57 04](https://user-images.githubusercontent.com/4949000/94665423-6988dc80-030c-11eb-957b-5452acef5fba.png)

## Output of `topping.id` in `countPizzasInToppings()` function
The different ID's are what leads to the multiple "Mushrooms" links in the filters section

![Screen Shot 2020-09-30 at 10 59 57](https://user-images.githubusercontent.com/4949000/94665542-92a96d00-030c-11eb-8d0f-65694f579dcd.png)

**Comment by gregdeane** [comment]
Now I'm thinking this is related to the fact that earlier in the lesson we manually added a few toppings, then later we used `sanity dataset import`. Perhaps `--replace` isn't working correctly?

**Comment by gregdeane** [comment]
So indeed it was the earlier manual additions and the later `sanity dataset import`. If I delete everything, then only run the import, all is well.

**Comment by Asjas** [comment]
Yeah, it was mentioned in Slack as well, the 2 example pizzas show up as separate after importing the dataset. Clearing those 2 example pizzas fixes it 👍

**Comment by gregdeane** [comment]
I've not had any luck getting into the Slack group. Something wrong with my invite. I DM'd @wesbos via Twitter and he mentioned he'd send me a new invite. Hope to join soon!
