### ISSUE TITLE
styling elements through their attributes

### ISSUE THREAD

**Issue by Manimall** [wesbos/master-gatsby#57]
![2020-10-20_22-44-58](https://user-images.githubusercontent.com/2580719/96636762-6d65b880-1326-11eb-8ec2-e98949016498.png)
 Typescript-styled-plugin is complaining

if i wrote smth like this - 

```
.gatsby-image-wrapper img[src*=base64\\] {
```
Unfortunately, this won't work

However, i found solution - 

```
.gatsby-image-wrapper img[${'src*=base64\\,'}] {
```
this will do the trick)

**Comment by wesbos** [comment]
thanks a ton!
