### ISSUE TITLE
ES modules

### ISSUE THREAD

**Issue by Shramkoweb** [wesbos/master-gatsby#74]
Hi. Can you help me? I have problems with ES modules & gatsby-config. 
[Link to failed build
](https://www.gatsbyjs.com/dashboard/64cf4698-d673-4790-8b97-d56b0c7f63ae/sites/465e2498-263a-4ba6-ba3f-153d19ea05bc/builds/3cd3549c-9bc7-4553-83a8-f80b17b30ec4/details#rawLogs)<img width="902" alt="image" src="https://user-images.githubusercontent.com/42001531/102701767-16fff200-4263-11eb-923c-90d3316afedc.png">

**Comment by Shramkoweb** [comment]
Import in config:

```
import dotenv from "dotenv";

dotenv.config({ path: ".env" });
```

scripts:
```
  "scripts": {
    "build": "cross-env NODE_OPTIONS=\"-r esm\" gatsby build",
    "develop": "cross-env NODE_OPTIONS=\"-r esm\" gatsby develop",
    "start": "npm run develop",
    "serve": "cross-env NODE_OPTIONS=\"-r esm\" gatsby serve",
    "clean": "gatsby clean",
    "netlify": "netlify dev",
    "prebuild": "netlify-lambda install"
  },
  ```

**Comment by Asjas** [comment]
@Shramkoweb You need to use `npm run start` or `npm run develop` to start the Gatsby server. You cannot use the global `gatsby develop` command as it won't work 🙂

**Comment by Shramkoweb** [comment]
@Asjas its work before I add dotenv... in wesbos example I see the same config. Why do they work?

**Comment by Asjas** [comment]
Gatsby does not support ES Modules. You have to use the npm scripts as they use the `esm` package to provide support for ES Modules.

**Comment by Shramkoweb** [comment]
Can u explain to me pls?  How I heed change scripts block in my app to correct work?

**Comment by Asjas** [comment]
You do not need to make any changes to your scripts as they are already correct, Wes configured it correctly in the starter files. You need to use the npm script and not the global Gatsby commands and it will work. 🙂

**Comment by Shramkoweb** [comment]
So I cant use Gatsby Cloud because I cant set the build command to `npm run build`?

**Comment by Asjas** [comment]
You can read the article at Gatsby Cloud on how to support ESM. They require that you make changes to the files for it to work on Gatsby Cloud. 🙂 

https://support.gatsbyjs.com/hc/en-us/articles/1500000294121-Using-ES6-Module-Syntax-in-Gatsby-API-Files-on-Gatsby-Cloud

**Comment by Shramkoweb** [comment]
@Asjas thx 🙏.
