### ISSUE TITLE
Need to deploy sanity graphql API to be able to use source plugin

### ISSUE THREAD

**Issue by matt-peck-masheen** [wesbos/master-gatsby#76]
Module #5 / Video #17 
The video adds the gatsby-source-sanity plugin to gatsby-config. I was unable to get `npm start` to work after updating the file and received this error message in the terminal:

<img width="1211" alt="Screen Shot 2021-01-03 at 12 30 36 PM" src="https://user-images.githubusercontent.com/46230191/103484862-f639af80-4dbf-11eb-9117-ff4d274e9de2.png">

After trying a few things I visited this link: https://github.com/sanity-io/gatsby-source-sanity#basic-usage

Key sentence:
"You should redeploy the GraphQL API everytime you make changes to the schema that you want to use in Gatsby by running sanity graphql deploy from within your Sanity project directory"

I had to open up the sanity folder in the project and run the command `sanity graphql deploy` and the I was able to run `npm start` again successfully.

**Comment by wesbos** [comment]
Thanks! This is part of the course though. Perhaps you missed it?

**Comment by matt-peck** [comment]
SOrry about the dupicate issues, I have too many GitHub accounts lol
