### ISSUE TITLE
Netlify deploy fail

### ISSUE THREAD

**Issue by ShaifArfan** [wesbos/master-gatsby#80]
Is there anyone who can help me? I am stuck with this for a long time.

failed Building production JavaScript and CSS bundles - 52.318s
6:26:29 AM: error Generating JavaScript bundles failed
6:26:29 AM: Can't resolve 'Gatsby-image' in '/opt/build/repo/gatsby/src/templates'
6:26:29 AM: If you're trying to use a package make sure that 'Gatsby-image' is installed. If you're trying to use a local file make sure that the path is correct.
6:26:29 AM: npm ERR! code ELIFECYCLE
6:26:29 AM: npm ERR! errno 1
6:26:29 AM: npm ERR! slicks-slices-frontend@0.1.0 build: `cross-env NODE_OPTIONS="-r esm" gatsby build`
6:26:29 AM: npm ERR! Exit status 1
6:26:29 AM: npm ERR!
6:26:29 AM: npm ERR! Failed at the slicks-slices-frontend@0.1.0 build script.
6:26:29 AM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
6:26:29 AM: npm ERR! A complete log of this run can be found in:
6:26:29 AM: npm ERR!     /opt/buildhome/.npm/_logs/2021-01-18T00_26_29_959Z-debug.log
6:26:29 AM: ​
6:26:29 AM: ────────────────────────────────────────────────────────────────
6:26:29 AM:   "build.command" failed                                        
6:26:29 AM: ────────────────────────────────────────────────────────────────
6:26:29 AM: ​
6:26:29 AM:   Error message
6:26:29 AM:   Command failed with exit code 1: CI= npm run build
6:26:29 AM: ​
6:26:29 AM:   Error location
6:26:29 AM:   In Build command from Netlify app:
6:26:29 AM:   CI= npm run build
6:26:29 AM: ​
6:26:29 AM:   Resolved config
6:26:29 AM:   build:
6:26:29 AM:     base: /opt/build/repo/gatsby
6:26:29 AM:     command: CI= npm run build
6:26:29 AM:     commandOrigin: ui
6:26:29 AM:     environment:
6:26:29 AM:       - CI
6:26:29 AM:       - GATSBY_GRAPHQL_ENDPOINT
6:26:29 AM:       - GATSBY_PAGE_SIZE
6:26:29 AM:       - GATSBY_SERVERLESS_BASE
6:26:29 AM:       - MAIL_HOST
6:26:29 AM:       - MAIL_PASS
6:26:29 AM:       - MAIL_USER
6:26:29 AM:       - NODE_VERSION
6:26:29 AM:       - SANITY_TOKEN
6:26:29 AM:     functions: /opt/build/repo/gatsby/functions
6:26:29 AM:     publish: /opt/build/repo/gatsby/public
6:26:30 AM: Caching artifacts

**Comment by Asjas** [comment]
Check your capitilization of the gatsby-image package. This is your error 🙂 @ShaifArfan 
```
Can't resolve 'Gatsby-image' in '/opt/build/repo/gatsby/src/templates'
```

**Comment by ShaifArfan** [comment]
Thanks.
